version: 2
jobs:
  build:
    docker:
      - image: fedora:32
    steps:
      - checkout
      - run: sudo dnf install tree
      - run: tree
  test:
    docker:
      - image: fedora:32
    steps:
      - checkout
      - run: pwd
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
