version: 2
jobs:
  build:
    docker:
      - image: fedora:32
    steps:
      - checkout
      - run: echo "---> Building!!!"
  test:
    docker:
      - image: fedora:32
    steps:
      - checkout
      - run: echo "---> Testing!!!"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
