version: 2
jobs:
  test:
    docker:
      - image: fedora:32
    steps:
      - checkout
      - run: sudo dnf install tree make ansible -y
      - run: tree
      - run: echo $ANSIBLE_VAULT_PASSWORD > $DEFAULT_VAULT_PASSWORD_FILE
      - run: ansible-playbook ./docker/play_local.yaml
          --extra-vars @./docker/profile.yaml
          -e variable_host=podman
          -e ansible_user=root
          -e sys_user=test
          --start-at-task "Add management public key to target systems"
workflows:
  version: 2
  setup_and_test:
    jobs:
      - test
