- name: Ensure the local system has a proper hostname
  hostname: name="fedora-{{ 999999 | random }}"
  when: "'fedora-' not in ansible_hostname"

- name: Add management public key to target systems
  authorized_key: 
    user: "{{ item }}"
    key: "{{ public_key_value }}"
  with_items:
    - root
    - "{{ sys_user }}"
  when: public_key_value is defined

- name: Deploy key-pairs
  copy:
    content: "{{ item.value.key_value }}"
    dest: "/home/{{ sys_user }}/.ssh/{{ item.value.key_name }}"
    owner: "{{ sys_user }}"
    group: "{{ sys_user }}"
    mode: 0600
  no_log: true
  with_dict: "{{ keys }}"

- name: "Update remote user >>{{ sys_user }}<< ssh-config"
  template:
    dest: "/home/{{ sys_user }}/.ssh/config"
    src: ../templates/ssh-config.j2
    owner: "{{ sys_user }}"
    group: "{{ sys_user }}"
    mode: 0644

- name: Ensure extra RPM repos are present
  copy:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644
  with_fileglob: ../files/yum-repos/*.repo

- name: Make sure base-system packages are up to date
  dnf:
    name: "*"
    state: latest
  register: system_update

- name: Restart the machine
  shell: sleep 2 && shutdown -r now "Ansible triggered restart"
  async: 1
  poll: 0
  ignore_errors: yes
  when: reboot
      
- name: Wait for system to come online
  wait_for_connection:
    delay: 60
    sleep: 5
    timeout: 900
  when: reboot

- name: Make sure local system has basic packages installed and up to date
  dnf:
    name: "{{ dnf_basic }}"
    state: latest