---
# tasks file for fedora_workstation

- name: Users and privileges
  ansible.builtin.import_tasks: 00-users.yaml

- name: Base system configuration
  ansible.builtin.import_tasks: 10-system.yaml

- name: Third-party tooling
  ansible.builtin.import_tasks: 20-tools.yaml

- name: Source code repositories
  ansible.builtin.import_tasks: 30-repos.yaml
  when: get_repos | bool
