---
galaxy_info:
  author: Miguel Pereira
  description: Simple, opinionated Fedora Workstation setup role
  company: onemorepereira.io

  license: GPL-3.0-only

  min_ansible_version: "2.16"

  platforms:
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - fedora
    - workstation
    - bootstrap

dependencies: []
