---
# Defining a bootstrap
basic_setup: true
basic_updates: true
basic_config: true
get_repos: true
reboot: true
sys_user: tsawyer
public_key_value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6Ozw992fHH8XwdC5z+t7n2NwyIAAyCZ1nE2JrsFF/BTOch/JxC8lTy/GErqxxOIa1LSp5OpcDLB/YOG15aLMOGuc5D/t0rndQug+DIIUuKNpmc4v951b3aw6lsePhS+ks87hQAVxLWKsF8UU/+ewypGJ6cfivv1xrWKIoSVjWlCLkbnQRkqsZE7WP5R8Y71rDacYOq8HfGvTqBtaN/8jtkKGU4Z6If9q8kz5vAFhFwxRh7FiDPwqVbkGhoqFxEFFCfd7HWA0uIXCkoxFI29bnJw0xIDlO4zWYoavlNcS+8uTy0Urihn+R/s3oOm/xhfj3PKgNbxXEYnuKsi7jAx2F"
sys_user_email: "tom.sawyer@2112.xyz"
git_nickname: zawyerhazcodez
default_identity_key_file: id_rsa

binaries_remote_archived: 
  packer: https://releases.hashicorp.com/packer/1.4.5/packer_1.4.5_linux_amd64.zip
  eksctl: https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_Linux_amd64.tar.gz

binaries_remote:
  kops:     https://github.com/kubernetes/kops/releases/download/1.15.0/kops-linux-amd64

installers:
  awscli-bundle:  https://s3.amazonaws.com/aws-cli/awscli-bundle.zip

boto_aws_region: "us-west-2"
boto_aws_region_endpoint: "ec2.us-west-2.amazonaws.com"
s3_main_bucket_region_url: "s3.amazonaws.com"

dnf_basic:
  - zip
  - unzip
  - ansible
  - yum-utils
  - jq

dnf_extras:
  - gvfs-mtp
  - simple-mtpfs

pip_basic:
  # - markdown
